# Generated by Django 5.2.14 on 2026-05-16 17:54

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='posts/')),
                ('summary', models.TextField()),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Nội dung bài viết')),
                ('author', models.CharField(default='TravelHub', max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
